"""empty message

Revision ID: 355888d9b6ab
Revises: 85cfc964cf16
Create Date: 2019-06-22 10:29:15.221589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355888d9b6ab'
down_revision = '85cfc964cf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'count')
    # ### end Alembic commands ###
