"""empty message

Revision ID: 4d7aa021a6ef
Revises: a133b0fa9a28
Create Date: 2019-06-22 16:58:52.002461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7aa021a6ef'
down_revision = 'a133b0fa9a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('fatherid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'fatherid')
    # ### end Alembic commands ###
