"""empty message

Revision ID: b4a37b8dfacd
Revises: 11f5bbe000ed
Create Date: 2019-06-27 20:16:11.371291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a37b8dfacd'
down_revision = '11f5bbe000ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('counts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'counts')
    # ### end Alembic commands ###
