"""empty message

Revision ID: b60a7cc3182f
Revises: dd00d1b13cda
Create Date: 2019-06-23 12:04:00.926997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60a7cc3182f'
down_revision = 'dd00d1b13cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('descript', sa.Text(length=500), nullable=True))
    op.add_column('article', sa.Column('keyword', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('tel', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tel')
    op.drop_column('article', 'keyword')
    op.drop_column('article', 'descript')
    # ### end Alembic commands ###
