"""empty message

Revision ID: dd00d1b13cda
Revises: 60f85d7dee4f
Create Date: 2019-06-22 17:14:18.682351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd00d1b13cda'
down_revision = '60f85d7dee4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('fatherid', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'fatherid')
    # ### end Alembic commands ###
